/** docs/tracks.excalidraw is generated by scripts/tracks_diagram.mjs; every binding must point at a real element. */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const here = dirname(fileURLToPath(import.meta.url));
const file = JSON.parse(readFileSync(join(here, "../../../docs/tracks.excalidraw"), "utf8")) as {
  type: string;
  version: number;
  elements: Array<{
    id: string;
    type: string;
    isDeleted: boolean;
    containerId?: string | null;
    boundElements?: Array<{ id: string; type: string }>;
    startBinding?: { elementId: string } | null;
    endBinding?: { elementId: string } | null;
    text?: string;
  }>;
};

describe("docs/tracks.excalidraw", () => {
  const ids = new Set(file.elements.map((e) => e.id));

  it("is an Excalidraw v2 file with unique element ids", () => {
    expect(file.type).toBe("excalidraw");
    expect(file.version).toBe(2);
    expect(ids.size).toBe(file.elements.length);
    expect(file.elements.some((e) => e.isDeleted)).toBe(false);
  });

  it("binds every arrow, label and bound element to an existing element", () => {
    for (const e of file.elements) {
      if (e.type === "arrow") {
        expect(e.startBinding && ids.has(e.startBinding.elementId), `${e.id} start`).toBe(true);
        expect(e.endBinding && ids.has(e.endBinding.elementId), `${e.id} end`).toBe(true);
      }
      if (e.containerId) expect(ids.has(e.containerId), `${e.id} container`).toBe(true);
      for (const b of e.boundElements ?? []) expect(ids.has(b.id), `${e.id} bound ${b.id}`).toBe(true);
    }
  });

  it("names the three tracks and the four stages", () => {
    const text = file.elements.map((e) => e.text ?? "").join("\n");
    for (const needle of ["Pyth", "Tessera", "PreStocks", "①", "②", "③", "④", "max_publish_age"]) {
      expect(text, needle).toContain(needle);
    }
  });
});
